In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

# Creating Array --> one dementional

In [6]:
import numpy as np

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# convert list to array 

In [10]:
l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

In [11]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

# access an element of array --> a[index]

In [12]:
a[2]

np.int64(3)

# change elements to sth else

In [13]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

# create a range from 0 to 9

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# start from sth other than 0

In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

# Create an arrays filled with numbers between firts and second parameters with size

In [16]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Multi-Dementional Array --> np.zeros((rows,columns))

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# Multi-Dementional Array from python List

In [18]:
n = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])

In [66]:
n[0, 0] = 10
n[0 , 1] = 20
n

array([[10, 20, 30],
       [ 4, 60,  6],
       [ 7, 70,  9]])

# Access row

In [20]:
n[0]

array([ 1, 20,  3])

In [21]:
n[0] = [10, 20, 30]
n

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# Access columns

In [22]:
n[:,1]

array([20,  5,  8])

In [23]:
n[: , 1] = [50, 60, 70]
n

array([[10, 50, 30],
       [ 4, 60,  6],
       [ 7, 70,  9]])

# Randomly Generated Array

In [24]:
np.random.seed(2) # if set seed, will always generate the same random numbers
np.random.rand(3, 3) # returns random numbers from 0 to 1

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

# define integer random array 

In [25]:
100 * np.random.rand(3, 3) # returns random numbers from 0 to 100

array([[26.68272751, 62.11338328, 52.91420943],
       [13.45799453, 51.35781213, 18.44398656],
       [78.53351478, 85.39752926, 49.42368374]])

In [26]:
np.random.randint(low= 0, high=10, size=(3,3)) # random integers from 0 to 10

array([[3, 5, 8],
       [4, 6, 3],
       [9, 2, 0]])

# Element-Wise Operations with Numpy
# We want to add/Multiply/Devide/Subtract to all the elements of the array 
# in Python (like usual python list) we need to write a for loop but here numpy let us just simply add it

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a + 1


array([1, 2, 3, 4, 5])

In [29]:
a * 2

array([0, 2, 4, 6, 8])

# Compaision Operations

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
a[a>= 2]

array([2, 3, 4])

# Other Operations

In [32]:
a.min()
a.max()
a.sum()
a.mean() # average
a.std() # standard deviation

np.float64(1.4142135623730951)

# Session 1.8 - linear Algebra

In [33]:
# vectore operations - Multiplication  - Matrix inverse

In [34]:
a = np.array([1,2,3])
x = 2 * a
x

array([2, 4, 6])

In [35]:
b = np.array([4,5,6])

a + b

array([5, 7, 9])

# Multiplication

In [36]:
# 1. vectore - vectore multiplication - 2. Matrix - vectore multiplication - 3. Matrix - Matrix multiplication

In [37]:
# this is element-wise multiplication but vector-vector multiplication is different and in linear algebra it is called dot product  
a * b


array([ 4, 10, 18])

# 1. vectore - vectore multiplication (dot/inner product)

In [38]:
# two ways to do dot product : 1. for loop and 2. numpy function

In [39]:
a.shape, b.shape

((3,), (3,))

In [40]:
a.shape[0] , b.shape[0]

(3, 3)

In [41]:
# 1.
def vector_vector_multi(a, b):
    n = a.shape[0]
    result = 0
    for i in range(n):
        result += a[i] * b[i]
    return result

r = vector_vector_multi(a, b)
print(r)




32


In [42]:
# 2.
r2 = a.dot(b)
print(r2)

32


# 2. Matrix - vectore multiplication

In [43]:
u = np.array([[2, 4, 5, 6],
             [1, 2, 1, 2],
             [3, 1, 2, 1]])
u.shape


(3, 4)

In [44]:
v = np.array([1, 0, 0, 2])

v.shape[0]

4

In [45]:
def matrix_vector_multi(u, v):
    assert u.shape[1] == v.shape[0] # check if the number of columns in u is equal to the number of rows in v
    m = u.shape[0] # number of rows in u
    result = np.zeros(m)

    for i in range(m):
        result[i] = vector_vector_multi(u[i] , v)
    return result

matrix_vector_multi(u, v)

array([14.,  5.,  5.])

# 3. Matrix - Matrix multiplication

In [ ]:
v = np.array([[1, 1, 2],
             [0, 0.5, 1],
             [0, 2, 1],
             [2, 1, 0]])
v.shape

In [47]:
def matrix_matrix_multi(u, v):
    assert u.shape[1] == v.shape[0]

    num_rows_u = u.shape[0]
    num_cols_v = v.shape[1]

    result = np.zeros((num_rows_u, num_cols_v))

    for i in range(num_rows_u):
        for j in range(num_cols_v):
            result[i, j] = vector_vector_multi(u[i], v[:, j])
    return result



In [48]:
# approach 2 
# def matrix_matrix_multi(u, v):
#     assert u.shape[1] == v.shape[0]
#     num_rows_u = u.shape[0]
#     num_cols_v = v.shape[1]

#     result = np.zeros((num_rows_u, num_cols_v))

#     for i in range(num_cols_v):
#         result[:, i] = matrix_vector_multi(u, v[:, i])
#     return result



In [49]:
matrix_matrix_multi(u, v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [50]:
# approach 3 - numpy function
u.dot(v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity Matrix

In [51]:
I = np.eye(4,3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [52]:
u.dot(I)

array([[2., 4., 5.],
       [1., 2., 1.],
       [3., 1., 2.]])

# Inverse Matrix


In [87]:

A = np.array([[2, 4, 5],
             [1, 2, 1],
             [3, 1, 2],
             [0, 2, 1]])
A.shape
As = A[[0, 1, 2]] # A need to be square matrix to able to do inverse

As.shape
As

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [88]:
A_minus = np.linalg.inv(As)
A_minus

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [90]:
A_minus.dot(As)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])